# -*- coding: utf-8 -*-
"""12 day program.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vfJr-3NXgs3x77jfUn4xSAhmqyIWKcsF
"""

from itertools import count
for i in count(20):
  if all(map(lambda x: i % x == 0, range(1, 21))):
    print(i)
    break

for a in range(0,1000):
  for b in range(a+1, 1000 - a):
    c = (1000-a-b) 
    if ((a**2 + b**2) == c**2) & (c > b) :
      print(f"a, b, c are {a, b, c}")

def convert_binary(x):
  lst = []
  while x>=1:
    y = (x%2)
    x = int(x/2)
    lst.append(y)
  return lst

convert_binary(7)

def check_palindrome(x):
  n = len(x)
  for i in range(1, (n//2)+1):
    if n%2 ==0:
      if x[(n//2) - i] != x[(n//2) + i - 1]:
       return 0
    if n%2 != 0:
      if x[(n//2) - i] != x[(n//2) + i]:
       return 0

check_palindrome('585')

check_palindrome(convert_binary(586))

list = []
for x in range(1000001):
  if (check_palindrome(str(x))!= 0) and (check_palindrome(convert_binary(x)) != 0):
    list.append(x) 
print(list)

from collections import Counter 
x = 'abcdc'
c = Counter(x)
print(c)

import pandas as pd

df = pd.read_csv('Value_of_Energy_Cost_Savings_Program_Savings_for_Businesses_-_FY2020.csv')

df.info()

#How many different companies are represented in the data set?
df['Company Name'].nunique()

#What is the total number of jobs created for businesses in Queens?
df[df['City'] == 'Queens']['Job created'].sum()

#How many different unique email domains names are there in the data set?
df['company email']

#How many different unique email domains names are there in the data set?
df['email_domain'] = df['company email'].str.split('@').str[1]
df['email_domain'].dropna().nunique()

#Considering only NTAs with at least 5 listed businesses, what is the average total savings and the total jobs created for each NTA?
df1 = df.groupby('NTA').agg({'company contact': count, 'Total Savings': mean(), 'Job created': sum()})
df1[df1['company contact']>= 5]

